export const smallOnly = 'only screen and (max-width: 40em)';
export const fontSizeBase = '1rem';
export const xSmPadding = '0.57rem'; // aprox 8px
export const smPadding = '1.15rem'; // aprox 16px
export const mdPadding = '1.715rem'; // aprox 24px
export const colorWhite = 'var(--color-white, #FFFFFF)';
export const colorPrimary = 'var(--color-primary, #0F70D7)';
export const colorTextDefault = 'var(--apps-panel-text-color, #393C48)';
export const colorTextLight = 'var(--color-text-light, #717C91)';
export const btnPrimaryHoverBg = 'var(--btn-primary-hover-bg, #0C57A7)';
export const colorGray = 'var(--color-gray, #4E5A66)';
export const colorGrayDark = 'var(--color-gray-dark, #06172A)';
export const colorGrayLight = 'var(--color-gray-light, #8B9AA8)';
export const colorGrayLighter = 'var(--color-gray-lighter, #A7B3BD)';
export const colorGrayIcons = 'var(--color-gray-icons, #909CAF)';
export const colorBackground = 'var(--color-background, #102133)';
export const colorText = `var(--color-text, ${colorGray})`;
export const colorHeading = `var(--color-heading, ${colorGrayDark})`;
